name: Release
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
  actions: write
jobs:
  test:
    uses: wesleytodd/fs-test-fixtures/.github/workflows/test-workflow.yml@next
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [test]
    outputs:
      releaseCreated: ${{ steps.releasePlease.outputs.release_created }}
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/release-please-action@v4
        name: Release Please
        id: releasePlease
        with:
          release-type: node
          token: ${{ secrets.GITHUB_TOKEN }}
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [release]
    if: ${{ needs.release.outputs.releaseCreated }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

